---
- name: install necessary packages
  apt:
    name:
      - apt-transport-https
      - software-properties-common
    force_apt_get: yes
    update_cache: yes

- name: add apt keys
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add apt repositories
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    filename: grafana
    state: present

- name: install grafana package
  apt:
    name: grafana
    force_apt_get: yes
    update_cache: yes
    autoclean: yes
    autoremove: yes
  notify:
    - restart grafana service
